In [7]:

import numpy as np
from collections import deque

class PuzzleState:
    def __init__(self, matrix, moves=0, previous=None):
        self.matrix = np.array(matrix)
        self.moves = moves
        self.previous = previous
        self.blank_position = tuple(np.argwhere(self.matrix == 0)[0])

    def is_goal(self):
        goal = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        return np.array_equal(self.matrix, goal)

    def generate_successors(self):
        successors = []
        x, y = self.blank_position
        possible_moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        
        for dx, dy in possible_moves:
            new_x, new_y = x + dx, y + dy
            if 0 <= new_x < 3 and 0 <= new_y < 3:
                new_matrix = self.matrix.copy()
                new_matrix[x, y], new_matrix[new_x, new_y] = new_matrix[new_x, new_y], new_matrix[x, y]
                successors.append(PuzzleState(new_matrix, self.moves + 1, self))
        return successors

def solve_puzzle(initial_state):
    start_state = PuzzleState(initial_state)
    if start_state.is_goal():
        print(start_state.matrix)
        return

    queue = deque([start_state])
    visited = set()
    visited.add(start_state.matrix.tobytes())

    while queue:
        current_state = queue.popleft()
        
        for successor in current_state.generate_successors():
            if successor.matrix.tobytes() not in visited:
                if successor.is_goal():
                    print(successor.matrix)
                    return
                queue.append(successor)
                visited.add(successor.matrix.tobytes())

if __name__ == "__main__":
    initial_state = [
        [1, 2, 3],
        [4, 8, 0],
        [7, 6, 5]
    ]
    
    solve_puzzle(initial_state)


[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [7]:
import numpy as np
from collections import deque

class PuzzleState:
    def __init__(self, matrix, moves=0, previous=None):
        self.matrix = np.array(matrix)
        self.moves = moves
        self.previous = previous
        self.blank_position = tuple(np.argwhere(self.matrix == 0)[0])
        self.heuristic = self.calculate_heuristic()

    def calculate_heuristic(self):
        goal = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        return np.sum(self.matrix != goal) - 1  # Subtracting 1 to exclude the blank tile

    def is_goal(self):
        goal = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        return np.array_equal(self.matrix, goal)

    def generate_successors(self):
        successors = []
        x, y = self.blank_position
        possible_moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        
        for dx, dy in possible_moves:
            new_x, new_y = x + dx, y + dy
            if 0 <= new_x < 3 and 0 <= new_y < 3:
                new_matrix = self.matrix.copy()
                new_matrix[x, y], new_matrix[new_x, new_y] = new_matrix[new_x, new_y], new_matrix[x, y]
                successors.append(PuzzleState(new_matrix, self.moves + 1, self))
        
        
        successors.sort(key=lambda state: state.heuristic)
        return successors

def solve_puzzle(initial_state):
    start_state = PuzzleState(initial_state)
    if start_state.is_goal():
        print_solution_path(start_state)
        return

    current_state = start_state
    visited = set()
    visited.add(current_state.matrix.tobytes())

    while not current_state.is_goal():
        successors = current_state.generate_successors()

        for successor in successors:
            if successor.matrix.tobytes() not in visited:
                current_state = successor
                visited.add(successor.matrix.tobytes())
                break
        
        if current_state.is_goal():
            print_solution_path(current_state)
            return

def print_solution_path(state):
    print(state.matrix)

if __name__ == "__main__":
    initial_state = [
        [1, 2, 3],
        [0, 4, 6],
        [7, 5, 8]
    ]
    
    solve_puzzle(initial_state)


[[1 2 3]
 [4 5 6]
 [7 8 0]]
